---

- name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition"
  when:
      - rhel8cis_rule_1_1_2_1_1
      - "'/tmp' not in mount_names"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - mounts
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - rule_1.1.2.1.1
  vars:
      warn_control_id: '1.1.2.1.1'
      required_mount: '/tmp'
  block:
      - name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} is not mounted on a separate partition"

      - name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
