---

## skips if mount is absent
- name: |
          "1.1.2.4.2 | PATCH | Ensure nodev option set on /var partition"
          "1.1.2.4.3 | PATCH | Ensure nosuid option set on /var partition"
  when:
      - "'/var' in mount_names"
      - item.mount == "/var"
      - rhel8cis_rule_1_1_2_4_2 or
        rhel8cis_rule_1_1_2_4_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.2.4.2
      - rule_1.1.2.4.3
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  notify: Change_requires_reboot
  ansible.posix.mount:
      name: /var
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_2_4_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_2_4_3 %}nosuid{% endif %}
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
