---

- name: "1.1.1.3 | PATCH | Ensure hfs kernel module is not available"
  when:
      - rhel8cis_rule_1_1_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.3
      - NIST800-53R5_CM-7
      - hfs
  block:
      - name: "1.1.1.3 | PATCH | Ensure hfs kernel module is not available | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install hfs(\\s|$)"
            line: "install hfs /bin/true"
            create: true
            mode: '0600'

      - name: "1.1.1.3 | PATCH | Ensure hfs kernel module is not available | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist hfs(\\s|$)"
            line: "blacklist hfs"
            create: true
            mode: '0600'

      - name: "1.1.1.3 | PATCH | Ensure hfs kernel module is not available | Disable squashfs"
        when:
            - not system_is_container
        community.general.modprobe:
            name: squashfs
            state: absent

