---

# skips if mount is absent
- name: |
          "1.1.2.7.2 | PATCH | Ensure nodev option set on /var/log/audit partition"
          "1.1.2.7.3 | PATCH | Ensure nosuid option set on /var/log/audit partition"
          "1.1.2.7.4 | PATCH | Ensure noexec option set on /var/log/audit partition"
  when:
      - "'/var/log/audit' in mount_names"
      - item.mount == "/var/log/audit"
      - rhel8cis_rule_1_1_2_7_2 or
        rhel8cis_rule_1_1_2_7_3 or
        rhel8cis_rule_1_1_2_7_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - rule_1.1.2.7.2
      - rule_1.1.2.7.3
      - rule_1.1.2.7.4
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  notify: Change_requires_reboot
  ansible.posix.mount:
      name: /var/log/audit
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_2_7_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_2_7_3 %}nosuid,{% endif %}{% if rhel8cis_rule_1_1_2_7_4 %}noexec{% endif %}
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
