---

- name: "1.7.1 | PATCH | Ensure message of the day is configured properly"
  when:
      - rhel8cis_rule_1_7_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - banner
      - patch
      - NIST800-53R5_CM-1
      - NIST800-53R5_CM-3
      - NIST800-53R5_CM-6
      - rule_1.7.1
  ansible.builtin.template:
      src: etc/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: go-rx

- name: "1.7.4 | PATCH | Ensure access to /etc/motd is configured"
  when:
      - rhel8cis_rule_1_7_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - perms
      - patch
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - rule_1.7.4
  ansible.builtin.file:
      path: /etc/motd
      state: file
      owner: root
      group: root
      mode: go-wx
