---

- name: "4.3.6 | PATCH | Ensure sudo authentication timeout is configured correctly"
  when:
      - rhel8cis_rule_4_3_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sudo
      - rule_4.3.6
  block:
      - name: "4.3.6 | AUDIT | Ensure sudo authentication timeout is configured correctly | Get files with timeout set"
        ansible.builtin.shell: grep -is 'timestamp_timeout' /etc/sudoers /etc/sudoers.d/* | cut -d":" -f1 | uniq | sort
        changed_when: false
        failed_when: false
        register: rhel8cis_4_3_6_timeout_files

      - name: "4.3.6 | PATCH | Ensure sudo authentication timeout is configured correctly | Set value if no results"
        when: rhel8cis_4_3_6_timeout_files.stdout | length == 0
        ansible.builtin.lineinfile:
            path: /etc/sudoers
            regexp: 'Defaults timestamp_timeout='
            line: "Defaults timestamp_timeout={{ rhel8cis_sudo_timestamp_timeout }}"
            validate: '/usr/sbin/visudo -cf %s'

      - name: "4.3.6 | PATCH | Ensure sudo authentication timeout is configured correctly | Set value if has results"
        when: rhel8cis_4_3_6_timeout_files.stdout | length > 0
        ansible.builtin.replace:
            path: "{{ item }}"
            regexp: 'timestamp_timeout=(\d+)'
            replace: "timestamp_timeout={{ rhel8cis_sudo_timestamp_timeout }}"
            validate: '/usr/sbin/visudo -cf %s'
        loop: "{{ rhel8cis_4_3_6_timeout_files.stdout_lines }}"

- name: "4.3.7 | PATCH | Ensure access to the su command is restricted"
  when:
      - rhel8cis_rule_4_3_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - sudo
      - rule_4.3.7
  block:
      - name: "4.3.7 | PATCH | Ensure access to the su command is restricted | Ensure sugroup exists"
        ansible.builtin.group:
            name: "{{ rhel8cis_sugroup }}"
            state: present
        register: rhel8cis_4_3_7_sugroup

      - name: "4.3.7 | PATCH | Ensure access to the su command is restricted | remove users from group"
        ansible.builtin.lineinfile:
            path: /etc/group
            regexp: '^{{ rhel8cis_sugroup }}(:.:.*:).*$'
            line: '{{ rhel8cis_sugroup }}\g<1>'
            backrefs: true

      - name: "4.3.7 | PATCH | Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth           required        pam_wheel.so use_uid group={{ rhel8cis_sugroup }}'
