---

- name: "4.5.3.2 | PATCH | Ensure default user shell timeout is configured"
  when:
      - rhel8cis_rule_4_5_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - shell
      - rule_4.5.3.2
  ansible.builtin.blockinfile:
      path: "{{ item.path }}"
      state: "{{ item.state }}"
      marker: "# {mark} - CIS benchmark - Ansible-lockdown"
      create: true
      mode: '0644'
      block: |
        TMOUT={{ rhel8cis_shell_session_timeout.timeout }}
        readonly TMOUT
        export TMOUT
  loop:
      - { path: "{{ rhel8cis_shell_session_timeout.file }}", state: present }
      - { path: /etc/profile, state: "{{ (rhel8cis_shell_session_timeout.file == '/etc/profile') | ternary('present', 'absent') }}" }
